words = [
    "Alonso",
    "Anpilogov",
    "Askaniy",
    "Astro",
    "BFGS",
    "BVR",
    "Bessell",
    "CALSPEC",
    "CDF",
    "CIE",
    "CMF",
    "FWHM",
    "LMS",
    "LOCALAPPDATA",
    "Lambertian",
    "MBOSS",
    "Photospectral",
    "Photospectrum",
    "Pinilla",
    "Pompeja",
    "SVO",
    "Salacia",
    "Stansberry",
    "TABLEDATA",
    "Tikhonov",
    "UBV",
    "UHDTV",
    "VOTABLE",
    "XDG",
    "XYZ",
    "allclose",
    "astrocolor",
    "bandpass",
    "cathetes",
    "cathetus",
    "certifi",
    "conftest",
    "cov",
    "desaturating",
    "downscaling",
    "exitance",
    "extrap",
    "extremal",
    "filterset",
    "getitem",
    "grav",
    "hyperspectral",
    "interp",
    "irradiances",
    "kms",
    "linalg",
    "mul",
    "multidim",
    "ndim",
    "newaxis",
    "npt",
    "pyplot",
    "pyright",
    "ror",
    "rtol",
    "scipy",
    "stds",
    "truediv",
    "urle",
    "urlopen",
]
